name: voila-hello-world-example
channels:
- conda-forge
dependencies:
- voila
- voila-material
- bqplot
- pandas
- numpy
- datetime
- openpyxl
- ipywidgets
- IPython
- matplotlib
- yfinance
- numpy_financial
- pyxlsb
- arctic
- pymongo
- dnspython
- pymongo[srv]
