name: voila-hello-world-example
channels:
- conda-forge
dependencies:
- voila
- voila-material
- bqplot
- pandas
- numpy
- openpyxl
- ipywidgets
- IPython
- matplotlib
- arctic
- pymongo
- dnspython
- pymongo[srv]
